### PR TITLE
fix: import cycle not allowed

### PR DESCRIPTION
**Pull request by proletarius101**
Same as https://github.com/emersion/go-message/pull/109

### CODE REVIEW

**Comment by proletarius101** [comment]
Then wait for https://github.com/emersion/go-message/pull/109

**Comment by emersion** [comment]
Does this also fix the same error? Maybe a linter gets executed and makes the packaging fail?

This patch looks good to me if you change the commit message to "utf7: fix package doc comment".

**Comment by proletarius101** [comment]
I guess so (they should really make it more clear). Commit message changed.

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
