### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by emersion**
Reject issues for questions about go-imap and IMAP in general. Our
issue tracker is filled with questions that aren't actionable.

cc @foxcpp

### CODE REVIEW

**Comment by foxcpp** [comment]
I would add a webchat link to help people who are not particularly familiar with IRC.

**Comment by emersion** [comment]
The `config.yml` should already display a link -- here's a preview of how that looks in Sway's issue tracker for instance:



> GitHub introduced "discussions" for that but looks like it is not available for repos as it is "beta"

I guess we _could_ enable it, but I wouldn't personally want to participate, watch or moderate it.

**Comment by foxcpp** [comment]
>A link in a text input isn't really clickable, so I haven't included it in the template.

Woops, I am a bit blind.

**Comment by emersion** [comment]
No worries :P alright, let's merge this and see how it goes.

**Comment by emersion** [comment]
Well, not so well… :/



Will push a fixup.

**Pull request merged**
