### PR TITLE
write: Solved problem with Store command

### PR DESCRIPTION
**Pull request by Frabec**
Solves the problem of issue #190

### CODE REVIEW

**Comment by emersion** [comment]
Thanks for you PR!

Would it be possible to instead change the string list to be an interface{} list? Otherwise we'd have to implement formatting for other list items too. You can use this function to do so: https://godoc.org/github.com/emersion/go-imap#FormatStringList

**Comment by Frabec** [comment]
I had tried at first to do as you say i.e convert the string list to an interface{} list. The problem is when I do that my postfix server throws me this error : 
`NO Error in IMAP command STORE: Flags list contains non-atoms (0.001 + 0.000 secs)`

**Comment by emersion** [comment]
Hmm. Can you try converting each `string` to an `imap.Atom`?

**Comment by Frabec** [comment]
Cool! You are right, it works now. I've just modified your function FormatStringList()

**Comment by emersion** [comment]
Hmm, I don't think this is right, because some other functions use `FormatStringList` and need escaping.

It seems that `client.Store` already has code to deal with this: https://github.com/emersion/go-imap/blob/v1/client/cmd_selected.go#L180

This makes me believe that this is actually a bug in go-imap-proxy. This function should convert the `[]string` into an `[]interface{}` containing strings: https://github.com/emersion/go-imap-proxy/blob/master/mailbox.go#L97

**Comment by Frabec** [comment]
I've checked the type of `value` in function https://github.com/emersion/go-imap-proxy/blob/master/mailbox.go#L97 when using the proxy and it is a `[]string`. I've added a line to fix the bug in go-imap-proxy. I've made a PR. 

Thanks for your help

**Pull request closed without merging**
