### PR TITLE
Add search for Gmail thread Id.

### PR DESCRIPTION
**Pull request by mariwilliam**
Gmail has implemented thread id (https://developers.google.com/gmail/imap/imap-extensions?hl=en#access_to_the_thread_id_x-gm-thrid)
This is a basic way to search messages with the Gmail thread id.

### CODE REVIEW

**Comment by emersion** [comment]
I would rather not add support for non-standard Google extensions.

**Comment by mariwilliam** [comment]
Alright, I thought other proprietary imap implementations may use a similar feature which we could "unify" around this parameter at some point.

**Comment by mariwilliam** [comment]
FYI I just added the ability to retrieve thread id from an email, I still believe this can be implemented as is and improved/extended later on with additional imap providers.

**Comment by emersion** [comment]
Sorry, but I think I'll reject this feature for now.

**Pull request closed without merging**
