### PR TITLE
close connection on failed write

### PR DESCRIPTION
**Pull request by danielkucera**
trying to fix following error:
```
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1797: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1796: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1797: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1796: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1797: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1796: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1797: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1796: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1797: write: broken pipe
Oct 22 15:19:31 speedy imap-tags[27635]: imap/server: 2019/10/22 15:19:31 cannot send response:  write tcp A:143->B:1796: write: broken pipe
```

### CODE REVIEW

**Comment by foxcpp** [comment]
Does it infinitely attempt to send the same response? It might be worth looking into reason why it is happening.  Also, there was https://github.com/foxcpp/maddy/issues/143. If you are not using the latest master, that might be your actual problem.

**Comment by emersion** [comment]
Just released 1.0.1 with the fix included.

**Comment by danielkucera** [comment]
I've updated to latest master, I'll report back. Thank you guys.

**Comment by danielkucera** [comment]
It doesn't seem to help. Happens to me after authentication also:

```
Oct 23 09:27:34 speedy systemd-journald[471]: Suppressed 37658 messages from imap-tags.service
Oct 23 09:27:34 speedy imap-tags[2284]: imap/server: 2019/10/23 09:27:34 cannot read command: read tcp A:143->B:58755: read: connection reset by peer
```

**Comment by horejsek** [comment]
I have the same problem. When used latest master with Outlook, it works, but using imap server with TB is doing this. When I set no `server.Debug`, then it fails right away, e.g. fails before anything can happen. When I pass some writer to `server.Debug`, it can do authentication, capability, id and select but fails on fetch. For now I don't know more.

**Comment by horejsek** [comment]
I recommend to turn on logs from the tool connecting to go-imap. My issue with broken pipe from Thundebird was because of not using raw QUOTA and QUOTAROOT responses from go-imap-quota extension. I submitted fix here: https://github.com/emersion/go-imap-quota/pull/7

**Pull request closed without merging**
