### PR TITLE
backendutil: Use textproto directly

### PR DESCRIPTION
**Pull request by foxcpp**

### CODE REVIEW

**Comment by foxcpp** [comment]
I think other backendutil functions should be updated too to use textproto.Header and raw io.Reader instead of message.Entity. Wdyt?

**Comment by emersion** [comment]
>I think other backendutil functions should be updated too to use textproto.Header and raw io.Reader instead of message.Entity. Wdyt?

Yup, that makes sense.

**Comment by foxcpp** [comment]
I'm unsure about FetchEnvelope, shouldn't it see decoded values for From, To, Subject, etc?

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
