### PR TITLE
go-imap v2 Backend interface work 

### LINKED ISSUE #323: Delegate updates dispatching to the backend
The exact problem is outlined in #318. As an alternative solution (and less hacky and buggy), I want to propose to redesign Backend interface in a way that completely moves update handling to the backend side. This includes EXPUNGE updates buffering and sequence numbers translation. This adds additional flexibility in implementation. For example, a backend using MVCC-enabled database can rely on it to provide consistent messages view for clients. Utilities that simplify implementations of rudimentary/naive backends can be added to backendutil package.

As a starting point, here is the snippet with a bunch of Go interfaces:
```go
type Conn interface {
  SendUpdate(u backend.Update)
}

type Backend interface {
  Login(conn Conn, username, password string) (Session, error)
}

type Session interface {
  OpenMbox(mbox string, readOnly bool) (Mailbox, error)
}

type Mailbox interface {
  ...
  Close() error
}
```

## Subtasks

- [ ] Remove existing updates handling code from go-imap/server
- [ ] Define Conn interface for backend and update Backend interfaces
- [ ] Implement utilities for simple backends

### PR DESCRIPTION
**Pull request by foxcpp**
See messages for individual commits.

Closes #323.

### CODE REVIEW

**Comment by foxcpp** [comment]
Okay, describing first commit in a greater detail:

1. backend.Updater is removed and this commit implements #323 with several adjustments. 
  Notably, User interface stays named User. Connection object is passed to GetMailbox instead.

2. backend.Mailbox interface is now solely reserved for operations on selected mailbox. This is 
  important to avoid calling now potentially more expensive GetMailbox for commands like
  SUBSCRIBE, STATUS that could be implemented without the need to establish sequence number
  view and update synchronization dance. This involves moving Status, SetSubscribed methods
  to User interface.

3. Initial Status call for Mailbox is squashed into GetMailbox operation. This is based on the 
  observation that requesting status information may involve operations that are also 
  performed when opening mailbox (establishing sequence numbers view). That is, it is likely 
  inexpensive for some backend implementations to do both operations at the same time.

**Comment by foxcpp** [comment]
Speaking of backendutil helpers, I extracted https://github.com/foxcpp/go-imap-sequpdate from my go-imap-maildir experiments. I am not putting it into this PR as I believe it is not polished out enough yet.

**Comment by foxcpp** [comment]
Note to self: go-imap-namespace needs updating for the new Interface

**Comment by foxcpp** [comment]
Note to self: SendUpdate might need synchronization.

**Comment by foxcpp** [comment]
Another note to self: Need to somehow workaround sending of updates in response to CLOSE. This is potentially harmful deviation from RFC 3501.

**Comment by foxcpp** [comment]
TODO: Documentation should be cleaned from Updater, etc references.

**Comment by foxcpp** [comment]
Just rebased it onto master. If we synchronize dev with master conflicts should be gone.

**Comment by emersion** [comment]
Closing because this is superseded by go-imap v2.

**Pull request closed without merging**
