### PR TITLE
imapclient: Close returned err.NetClosed after Logout

### PR DESCRIPTION
**Pull request by Rikkuru**
server closes connection after Logout and Close should not return error NetClosed when called after logout

### CODE REVIEW

**Comment by emersion** [comment]
Can we avoid using `%w` everywhere? That makes the underlying errors part of our API.

**Comment by Rikkuru** [comment]
> part

yes

**Comment by emersion** [comment]
Hm, it sounds like the test succeeds without the bugfix…

**Comment by Rikkuru** [comment]
> Hm, it sounds like the test succeeds without the bugfix…

That's strange. I was able to reproduce it locally 
I created a PR with test without this fix , lets see if test fail there too 
https://builds.sr.ht/~emersion/job/1110697

**Comment by Rikkuru** [comment]
https://github.com/emersion/go-imap/pull/567#issuecomment-1847277690

**Comment by emersion** [comment]
Thanks!

The test is still unreliable, but better than nothing.

**Pull request merged**
